// webpack/webpack-starter-kit/src/components/app.jsx
/* 
import React from 'react';

export class HelloWorld extends React.Component {} 
*/

import React, { Component } from 'react';

export class HelloWorld extends Component {
  render() {
    return (
      <div>
        {/* Todas estas props las cogemos de hello_react.js */}
        <h1>Webpack + {this.props.name}</h1>
        <p>Hola mundo, Webpack con {this.props.name}!</p>
        <nav className="menu">
          {this.props.menu.map(link => (
            <a key={link[0]} href={link[1]}>
              {link[0]}
            </a>
          ))}
        </nav>
        <img src={this.props.logo} />
      </div>
    );
  }
}

// webpack/webpack-starter-kit/src/components/app.vue
<template>
  <div id="app">
    <h1>Webpack + {{name}}</h1>
    <p>Hola mundo, Webpack con {{name}}</p>
    <nav class="menu">
      <a v-for="link in links" :href="link[1]" :key="link[0]" v-text="link[0]"></a>
    </nav>
    <img :src="logo">
  </div>
</template>

<script>
import style from "../style.css";
import sass from "../scss/main.scss";
import logo from "../img/vue-logo.png";
import data from "../data.json";

export default {
  data() {
    return {
      name: "Vue.js",
      logo: logo,
      links: data.links
    };
  }
};
</script>

<style>
</style>
